name: continuos training
permissions:  
  id-token: write 
  contents: write
  pull-requests: write 
  issues: read
  packages: none
on:
  push:
    branches:
      -  workflows_continuos_training
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT
jobs:
  continuos-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Decrypt Credentials
        env:

          CIPHERTEXT_ACCES_ID : ${{ secrets.CIPHERTEXT_ACCES_ID }}
          CIPHERTEXT_SECRET : ${{ secrets.CIPHERTEXT_SECRET }}
          ENCRYPTION_KEY_ACCES_ID : ${{ secrets.ENCRYPTION_KEY_ACCES_ID }}
          ENCRYPTION_KEY_HEX_SECRET : ${{ secrets.ENCRYPTION_KEY_HEX_SECRET }}
          IV_ACCES_ID : ${{ secrets.IV_ACCES_ID }}
          IV_SECRET : ${{ secrets.IV_SECRET }}

        run: |
          pip -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          export AWS_ACCES_KEY_ID=$(python utils/setter.py)
          export AWS_SECRET_ACCES_KEY=$(python utils/setter.py)
          dvc pull data/Dry_Bean.csv
          mv Dry_Bean.csv ./data/
          dvc repro -f
          echo 'Training Completed'
          dvc add model/model.pkl -r models_track --to-remote
          dvc push model/model.pkl -r models_track 

