name: Mlops
permissions:  
  id-token: write 
  contents: write
  pull-requests: write 
  issues: read
  packages: none
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT
jobs:
  continuos-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Decrypt Credentials
        env:
          CIPHERTEXT_ACCES_ID: ${{ secrets.CIPHERTEXT_ACCES_ID }}
          CIPHERTEXT_SECRET: ${{ secrets.CIPHERTEXT_SECRET }}
          ENCRYPTION_KEY_ACCES_ID: ${{ secrets.ENCRYPTION_KEY_ACCES_ID }}
          ENCRYPTION_KEY_HEX_SECRET: ${{ secrets.ENCRYPTION_KEY_HEX_SECRET }}
          IV_ACCES_ID: ${{ secrets.IV_ACCES_ID }}
          IV_SECRET: ${{ secrets.IV_SECRET }}
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          export AWS_ACCESS_KEY_ID=$(python utils/setter.py)
          export AWS_SECRET_ACCESS_KEY=$(python utils/setter.py)
          dvc pull data/Dry_Bean.csv
          mv data/Dry_Bean.csv ./data/
          dvc repro -f
          echo '
