name: Training
permissions:  
  id-token: write 
  contents: write
  pull-requests: write 
  issues: read
  packages: none

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Decrypt secrets access id and secret
        env:
          ENCRYPTION_KEY_ACCES_ID: ${{ secrets.ENCRYPTION_KEY_ACCES_ID }}
          IV_ACCES_ID: ${{ secrets.IV_ACCES_ID }}
          CIPHERTEXT_ACCES_ID: ${{ secrets.CIPHERTEXT_ACCES_ID }}
          ENCRYPTION_KEY_HEX_SECRET: ${{ secrets.ENCRYPTION_KEY_HEX_SECRET }}
          IV_SECRET: ${{ secrets.IV_SECRET }}
          CIPHERTEXT_SECRET: ${{ secrets.CIPHERTEXT_SECRET }}
        run: |
          python -m pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install pycryptodome
          python utils/setter.py

      - name: Train model
        run: |
          python -m pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          echo "Asignando las variables"
          export AWS_SECRET_ACCESS_KEY=$(cat aws_secret_key_id.txt)
          export AWS_ACCESS_KEY_ID=$(cat aws_access_key_id.txt)
          echo "Trayendo el modelo"
          dvc pull models/model.pkl -r aws-bucket-model
          dvc unprotect models/model.pkl.dvc
          dvc repro -f
          echo 'Training Completed'
          dvc add models/model.pkl --to-remote -r aws-bucket-model
          dvc push 

      - name: Clean up
        run: |
          rm -f aws_secret_key_id.txt
          rm -f aws_access_key_id.txt

      - name: Commit .dvc file changes
        run: |
          git config --local user.email "thegameprox777.13@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add .

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
        env:
          DEBUG: true

      - uses: iterative/setup-cml@v1

      - name: Push metrics
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.txt >> report.md
          cml comment create report.md
